//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public long ID { get; set; }

        [DisplayName("Tên")]
        [Required]
        public string Name { get; set; }

        [DisplayName("Địa chỉ")]
        [Required]
        public string Address { get; set; }

        [DisplayName("Email")]
        [Required]
        public string Email { get; set; }

        [DisplayName("Số điện thoại")]
        [Required]
        public string Phone { get; set; }
    }
}
