//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Manager
    {
        public long ID { get; set; }

        [DisplayName("Họ QTV")]
        [Required(ErrorMessage ="Họ quản trị viên không được để trông")]
        public string SirName { get; set; }

        [DisplayName("Tên QTV")]
        [Required(ErrorMessage = "Tên quản trị viên không được để trông")]
        public string FirstName { get; set; }

        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trông")]
        public string UserName { get; set; }

        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        public string Password { get; set; }

        [DisplayName("Trạng thái")]
        [Required]
        public Nullable<bool> Status { get; set; }

        [DisplayName("Nhóm")]
        public Nullable<long> GroupID { get; set; }

        public virtual ManagerGroup ManagerGroup { get; set; }
    }
}
