//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingRole
    {
        public long ManagerGroupID { get; set; }
        public long RoleID { get; set; }
        public string Note { get; set; }
    
        public virtual ManagerGroup ManagerGroup { get; set; }
        public virtual Role Role { get; set; }
    }
}
