//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long ID { get; set; }

        [DisplayName("Tên thể loại")]
        [Required(ErrorMessage ="Điền tên thể loại")]
        public string Name { get; set; }

        [DisplayName("Hình ảnh")]
        public string Image { get; set; }
        public string MetaTitle { get; set; }

        [DisplayName("Độ ưu tiên")]
        public Nullable<int> DisplayOrder { get; set; }

        [DisplayName("Ngày thêm")]
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [DisplayName("Người tạo")]
        public string CreatedBy { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
