//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public long ID { get; set; }

        [DisplayName("Tên sản phẩm")]
        public string Name { get; set; }
        public string MetaTitle { get; set; }

        [DisplayName("Mô tả")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Hình ảnh")]
        public string Image { get; set; }
        public string MoreImages { get; set; }

        [DisplayName("Tác giả")]
        public string Authors { get; set; }

        [DisplayName("Giá")]
        public Nullable<decimal> Price { get; set; }

        [DisplayName("Giảm giá")]
        public Nullable<decimal> PromotionPrice { get; set; }

        [DisplayName("Số lượng")]
        public int Quantity { get; set; }

        [DisplayName("Thể loại")]
        public Nullable<long> CategoryID { get; set; }

        [DisplayName("Chi tiết")]
        [DataType(DataType.MultilineText)]
        public string Detail { get; set; }

        [DisplayName("Ngày thêm")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> Status { get; set; }

        [DisplayName("Sản phẩm hot")]
        public Nullable<System.DateTime> TopHot { get; set; }

        [DisplayName("Lượt mua")]
        public Nullable<int> ViewCout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
